#!/bin/sh

# THIS SCRIPT IS FOR PROJECT MAINTAINER ONLY
# It is executed only to generate "configure"

set -x
aclocal -I config
autoheader
glibtoolize --copy --force # if linux, use libtoolize
automake --foreign --add-missing --copy
autoconf
